version: 2

updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "03:00"
      timezone: Etc/UTC
    open-pull-requests-limit: 5
    commit-message:
      prefix: deps(cargo)
    groups:
      cargo-minor-and-patch:
        patterns:
          - "*"
        update-types:
          - minor
          - patch

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "03:15"
      timezone: Etc/UTC
    open-pull-requests-limit: 5
    commit-message:
      prefix: deps(actions)
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: docker
    directory: /deploy
    schedule:
      interval: weekly
      day: monday
      time: "03:30"
      timezone: Etc/UTC
    open-pull-requests-limit: 5
    commit-message:
      prefix: deps(docker)
    groups:
      docker-images:
        patterns:
          - "*"

  - package-ecosystem: docker-compose
    directory: /deploy
    schedule:
      interval: weekly
      day: monday
      time: "03:45"
      timezone: Etc/UTC
    open-pull-requests-limit: 5
    commit-message:
      prefix: deps(compose)
    groups:
      compose-images:
        patterns:
          - "*"

