[package]
name = "rill3-db"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
chrono.workspace = true
hex.workspace = true
rill3-domain = { path = "../domain" }
sqlx.workspace = true
thiserror.workspace = true
url.workspace = true
uuid.workspace = true

[dev-dependencies]
tokio.workspace = true
